-- =============================================================================
-- Migration: Seed Painting Task Matrix
-- Date: 2026-01-19
-- Description: Populate painting_task_matrix with data from hardcoded matrix
-- =============================================================================

-- Clear existing data (if any)
DELETE FROM painting_task_matrix;

-- Reset auto_increment
ALTER TABLE painting_task_matrix AUTO_INCREMENT = 1;

-- =============================================================================
-- INSERT all matrix entries
-- Components: Face(0), Return(1), Trim(2), Return & Trim(3), Face & Return(4), Frame(5), All Sides(6)
-- Timings: Before Cutting(0), After Cutting(1), After Bending(2), After Fabrication(3)
-- =============================================================================

INSERT INTO painting_task_matrix (product_type, product_type_key, component, component_key, timing, timing_key, material_variant, task_numbers) VALUES
-- Front Lit (P1, P2, P2, P2, P3, NONE, NONE)
('Front Lit', 'front-lit', 'Face', 'face', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Front Lit', 'front-lit', 'Face', 'face', 'After Cutting', 'after-cutting', NULL, '[2,6]'),
('Front Lit', 'front-lit', 'Face', 'face', 'After Bending', 'after-bending', NULL, NULL),
('Front Lit', 'front-lit', 'Face', 'face', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Front Lit', 'front-lit', 'Return', 'return', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Front Lit', 'front-lit', 'Return', 'return', 'After Cutting', 'after-cutting', NULL, NULL),
('Front Lit', 'front-lit', 'Return', 'return', 'After Bending', 'after-bending', NULL, NULL),
('Front Lit', 'front-lit', 'Return', 'return', 'After Fabrication', 'after-fabrication', NULL, '[2,8]'),
('Front Lit', 'front-lit', 'Trim', 'trim', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Front Lit', 'front-lit', 'Trim', 'trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Front Lit', 'front-lit', 'Trim', 'trim', 'After Bending', 'after-bending', NULL, NULL),
('Front Lit', 'front-lit', 'Trim', 'trim', 'After Fabrication', 'after-fabrication', NULL, '[2,8]'),
('Front Lit', 'front-lit', 'Return & Trim', 'return-trim', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Front Lit', 'front-lit', 'Return & Trim', 'return-trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Front Lit', 'front-lit', 'Return & Trim', 'return-trim', 'After Bending', 'after-bending', NULL, NULL),
('Front Lit', 'front-lit', 'Return & Trim', 'return-trim', 'After Fabrication', 'after-fabrication', NULL, '[2,8]'),
('Front Lit', 'front-lit', 'Face & Return', 'face-return', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Front Lit', 'front-lit', 'Face & Return', 'face-return', 'After Cutting', 'after-cutting', NULL, '[2,3,6]'),
('Front Lit', 'front-lit', 'Face & Return', 'face-return', 'After Bending', 'after-bending', NULL, NULL),
('Front Lit', 'front-lit', 'Face & Return', 'face-return', 'After Fabrication', 'after-fabrication', NULL, '[2,8]'),
('Front Lit', 'front-lit', 'Frame', 'frame', 'Before Cutting', 'before-cutting', NULL, NULL),
('Front Lit', 'front-lit', 'Frame', 'frame', 'After Cutting', 'after-cutting', NULL, NULL),
('Front Lit', 'front-lit', 'Frame', 'frame', 'After Bending', 'after-bending', NULL, NULL),
('Front Lit', 'front-lit', 'Frame', 'frame', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Front Lit', 'front-lit', 'All Sides', 'all-sides', 'Before Cutting', 'before-cutting', NULL, NULL),
('Front Lit', 'front-lit', 'All Sides', 'all-sides', 'After Cutting', 'after-cutting', NULL, NULL),
('Front Lit', 'front-lit', 'All Sides', 'all-sides', 'After Bending', 'after-bending', NULL, NULL),
('Front Lit', 'front-lit', 'All Sides', 'all-sides', 'After Fabrication', 'after-fabrication', NULL, NULL),

-- Halo Lit
('Halo Lit', 'halo-lit', 'Face', 'face', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Halo Lit', 'halo-lit', 'Face', 'face', 'After Cutting', 'after-cutting', NULL, '[1,6]'),
('Halo Lit', 'halo-lit', 'Face', 'face', 'After Bending', 'after-bending', NULL, NULL),
('Halo Lit', 'halo-lit', 'Face', 'face', 'After Fabrication', 'after-fabrication', NULL, '[1,8]'),
('Halo Lit', 'halo-lit', 'Return', 'return', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Halo Lit', 'halo-lit', 'Return', 'return', 'After Cutting', 'after-cutting', NULL, NULL),
('Halo Lit', 'halo-lit', 'Return', 'return', 'After Bending', 'after-bending', NULL, NULL),
('Halo Lit', 'halo-lit', 'Return', 'return', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Halo Lit', 'halo-lit', 'Trim', 'trim', 'Before Cutting', 'before-cutting', NULL, NULL),
('Halo Lit', 'halo-lit', 'Trim', 'trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Halo Lit', 'halo-lit', 'Trim', 'trim', 'After Bending', 'after-bending', NULL, NULL),
('Halo Lit', 'halo-lit', 'Trim', 'trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Halo Lit', 'halo-lit', 'Return & Trim', 'return-trim', 'Before Cutting', 'before-cutting', NULL, NULL),
('Halo Lit', 'halo-lit', 'Return & Trim', 'return-trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Halo Lit', 'halo-lit', 'Return & Trim', 'return-trim', 'After Bending', 'after-bending', NULL, NULL),
('Halo Lit', 'halo-lit', 'Return & Trim', 'return-trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Halo Lit', 'halo-lit', 'Face & Return', 'face-return', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Halo Lit', 'halo-lit', 'Face & Return', 'face-return', 'After Cutting', 'after-cutting', NULL, '[1,2,3,6]'),
('Halo Lit', 'halo-lit', 'Face & Return', 'face-return', 'After Bending', 'after-bending', NULL, NULL),
('Halo Lit', 'halo-lit', 'Face & Return', 'face-return', 'After Fabrication', 'after-fabrication', NULL, '[1,8]'),
('Halo Lit', 'halo-lit', 'Frame', 'frame', 'Before Cutting', 'before-cutting', NULL, NULL),
('Halo Lit', 'halo-lit', 'Frame', 'frame', 'After Cutting', 'after-cutting', NULL, NULL),
('Halo Lit', 'halo-lit', 'Frame', 'frame', 'After Bending', 'after-bending', NULL, NULL),
('Halo Lit', 'halo-lit', 'Frame', 'frame', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Halo Lit', 'halo-lit', 'All Sides', 'all-sides', 'Before Cutting', 'before-cutting', NULL, NULL),
('Halo Lit', 'halo-lit', 'All Sides', 'all-sides', 'After Cutting', 'after-cutting', NULL, NULL),
('Halo Lit', 'halo-lit', 'All Sides', 'all-sides', 'After Bending', 'after-bending', NULL, NULL),
('Halo Lit', 'halo-lit', 'All Sides', 'all-sides', 'After Fabrication', 'after-fabrication', NULL, NULL),

-- Front Lit Acrylic Face (NONE, [[2,3], N, N, [1,8]], NONE, NONE, NONE, NONE, NONE)
('Front Lit Acrylic Face', 'front-lit-acrylic-face', 'Face', 'face', 'Before Cutting', 'before-cutting', NULL, NULL),
('Front Lit Acrylic Face', 'front-lit-acrylic-face', 'Face', 'face', 'After Cutting', 'after-cutting', NULL, NULL),
('Front Lit Acrylic Face', 'front-lit-acrylic-face', 'Face', 'face', 'After Bending', 'after-bending', NULL, NULL),
('Front Lit Acrylic Face', 'front-lit-acrylic-face', 'Face', 'face', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Front Lit Acrylic Face', 'front-lit-acrylic-face', 'Return', 'return', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Front Lit Acrylic Face', 'front-lit-acrylic-face', 'Return', 'return', 'After Cutting', 'after-cutting', NULL, NULL),
('Front Lit Acrylic Face', 'front-lit-acrylic-face', 'Return', 'return', 'After Bending', 'after-bending', NULL, NULL),
('Front Lit Acrylic Face', 'front-lit-acrylic-face', 'Return', 'return', 'After Fabrication', 'after-fabrication', NULL, '[1,8]'),
('Front Lit Acrylic Face', 'front-lit-acrylic-face', 'Trim', 'trim', 'Before Cutting', 'before-cutting', NULL, NULL),
('Front Lit Acrylic Face', 'front-lit-acrylic-face', 'Trim', 'trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Front Lit Acrylic Face', 'front-lit-acrylic-face', 'Trim', 'trim', 'After Bending', 'after-bending', NULL, NULL),
('Front Lit Acrylic Face', 'front-lit-acrylic-face', 'Trim', 'trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Front Lit Acrylic Face', 'front-lit-acrylic-face', 'Return & Trim', 'return-trim', 'Before Cutting', 'before-cutting', NULL, NULL),
('Front Lit Acrylic Face', 'front-lit-acrylic-face', 'Return & Trim', 'return-trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Front Lit Acrylic Face', 'front-lit-acrylic-face', 'Return & Trim', 'return-trim', 'After Bending', 'after-bending', NULL, NULL),
('Front Lit Acrylic Face', 'front-lit-acrylic-face', 'Return & Trim', 'return-trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Front Lit Acrylic Face', 'front-lit-acrylic-face', 'Face & Return', 'face-return', 'Before Cutting', 'before-cutting', NULL, NULL),
('Front Lit Acrylic Face', 'front-lit-acrylic-face', 'Face & Return', 'face-return', 'After Cutting', 'after-cutting', NULL, NULL),
('Front Lit Acrylic Face', 'front-lit-acrylic-face', 'Face & Return', 'face-return', 'After Bending', 'after-bending', NULL, NULL),
('Front Lit Acrylic Face', 'front-lit-acrylic-face', 'Face & Return', 'face-return', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Front Lit Acrylic Face', 'front-lit-acrylic-face', 'Frame', 'frame', 'Before Cutting', 'before-cutting', NULL, NULL),
('Front Lit Acrylic Face', 'front-lit-acrylic-face', 'Frame', 'frame', 'After Cutting', 'after-cutting', NULL, NULL),
('Front Lit Acrylic Face', 'front-lit-acrylic-face', 'Frame', 'frame', 'After Bending', 'after-bending', NULL, NULL),
('Front Lit Acrylic Face', 'front-lit-acrylic-face', 'Frame', 'frame', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Front Lit Acrylic Face', 'front-lit-acrylic-face', 'All Sides', 'all-sides', 'Before Cutting', 'before-cutting', NULL, NULL),
('Front Lit Acrylic Face', 'front-lit-acrylic-face', 'All Sides', 'all-sides', 'After Cutting', 'after-cutting', NULL, NULL),
('Front Lit Acrylic Face', 'front-lit-acrylic-face', 'All Sides', 'all-sides', 'After Bending', 'after-bending', NULL, NULL),
('Front Lit Acrylic Face', 'front-lit-acrylic-face', 'All Sides', 'all-sides', 'After Fabrication', 'after-fabrication', NULL, NULL),

-- Dual Lit - Single Layer (same as Front Lit)
('Dual Lit - Single Layer', 'dual-lit-single-layer', 'Face', 'face', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Dual Lit - Single Layer', 'dual-lit-single-layer', 'Face', 'face', 'After Cutting', 'after-cutting', NULL, '[2,6]'),
('Dual Lit - Single Layer', 'dual-lit-single-layer', 'Face', 'face', 'After Bending', 'after-bending', NULL, NULL),
('Dual Lit - Single Layer', 'dual-lit-single-layer', 'Face', 'face', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Dual Lit - Single Layer', 'dual-lit-single-layer', 'Return', 'return', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Dual Lit - Single Layer', 'dual-lit-single-layer', 'Return', 'return', 'After Cutting', 'after-cutting', NULL, NULL),
('Dual Lit - Single Layer', 'dual-lit-single-layer', 'Return', 'return', 'After Bending', 'after-bending', NULL, NULL),
('Dual Lit - Single Layer', 'dual-lit-single-layer', 'Return', 'return', 'After Fabrication', 'after-fabrication', NULL, '[2,8]'),
('Dual Lit - Single Layer', 'dual-lit-single-layer', 'Trim', 'trim', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Dual Lit - Single Layer', 'dual-lit-single-layer', 'Trim', 'trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Dual Lit - Single Layer', 'dual-lit-single-layer', 'Trim', 'trim', 'After Bending', 'after-bending', NULL, NULL),
('Dual Lit - Single Layer', 'dual-lit-single-layer', 'Trim', 'trim', 'After Fabrication', 'after-fabrication', NULL, '[2,8]'),
('Dual Lit - Single Layer', 'dual-lit-single-layer', 'Return & Trim', 'return-trim', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Dual Lit - Single Layer', 'dual-lit-single-layer', 'Return & Trim', 'return-trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Dual Lit - Single Layer', 'dual-lit-single-layer', 'Return & Trim', 'return-trim', 'After Bending', 'after-bending', NULL, NULL),
('Dual Lit - Single Layer', 'dual-lit-single-layer', 'Return & Trim', 'return-trim', 'After Fabrication', 'after-fabrication', NULL, '[2,8]'),
('Dual Lit - Single Layer', 'dual-lit-single-layer', 'Face & Return', 'face-return', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Dual Lit - Single Layer', 'dual-lit-single-layer', 'Face & Return', 'face-return', 'After Cutting', 'after-cutting', NULL, '[2,3,6]'),
('Dual Lit - Single Layer', 'dual-lit-single-layer', 'Face & Return', 'face-return', 'After Bending', 'after-bending', NULL, NULL),
('Dual Lit - Single Layer', 'dual-lit-single-layer', 'Face & Return', 'face-return', 'After Fabrication', 'after-fabrication', NULL, '[2,8]'),
('Dual Lit - Single Layer', 'dual-lit-single-layer', 'Frame', 'frame', 'Before Cutting', 'before-cutting', NULL, NULL),
('Dual Lit - Single Layer', 'dual-lit-single-layer', 'Frame', 'frame', 'After Cutting', 'after-cutting', NULL, NULL),
('Dual Lit - Single Layer', 'dual-lit-single-layer', 'Frame', 'frame', 'After Bending', 'after-bending', NULL, NULL),
('Dual Lit - Single Layer', 'dual-lit-single-layer', 'Frame', 'frame', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Dual Lit - Single Layer', 'dual-lit-single-layer', 'All Sides', 'all-sides', 'Before Cutting', 'before-cutting', NULL, NULL),
('Dual Lit - Single Layer', 'dual-lit-single-layer', 'All Sides', 'all-sides', 'After Cutting', 'after-cutting', NULL, NULL),
('Dual Lit - Single Layer', 'dual-lit-single-layer', 'All Sides', 'all-sides', 'After Bending', 'after-bending', NULL, NULL),
('Dual Lit - Single Layer', 'dual-lit-single-layer', 'All Sides', 'all-sides', 'After Fabrication', 'after-fabrication', NULL, NULL),

-- Dual Lit - Double Layer (same as Front Lit)
('Dual Lit - Double Layer', 'dual-lit-double-layer', 'Face', 'face', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Dual Lit - Double Layer', 'dual-lit-double-layer', 'Face', 'face', 'After Cutting', 'after-cutting', NULL, '[2,6]'),
('Dual Lit - Double Layer', 'dual-lit-double-layer', 'Face', 'face', 'After Bending', 'after-bending', NULL, NULL),
('Dual Lit - Double Layer', 'dual-lit-double-layer', 'Face', 'face', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Dual Lit - Double Layer', 'dual-lit-double-layer', 'Return', 'return', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Dual Lit - Double Layer', 'dual-lit-double-layer', 'Return', 'return', 'After Cutting', 'after-cutting', NULL, NULL),
('Dual Lit - Double Layer', 'dual-lit-double-layer', 'Return', 'return', 'After Bending', 'after-bending', NULL, NULL),
('Dual Lit - Double Layer', 'dual-lit-double-layer', 'Return', 'return', 'After Fabrication', 'after-fabrication', NULL, '[2,8]'),
('Dual Lit - Double Layer', 'dual-lit-double-layer', 'Trim', 'trim', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Dual Lit - Double Layer', 'dual-lit-double-layer', 'Trim', 'trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Dual Lit - Double Layer', 'dual-lit-double-layer', 'Trim', 'trim', 'After Bending', 'after-bending', NULL, NULL),
('Dual Lit - Double Layer', 'dual-lit-double-layer', 'Trim', 'trim', 'After Fabrication', 'after-fabrication', NULL, '[2,8]'),
('Dual Lit - Double Layer', 'dual-lit-double-layer', 'Return & Trim', 'return-trim', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Dual Lit - Double Layer', 'dual-lit-double-layer', 'Return & Trim', 'return-trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Dual Lit - Double Layer', 'dual-lit-double-layer', 'Return & Trim', 'return-trim', 'After Bending', 'after-bending', NULL, NULL),
('Dual Lit - Double Layer', 'dual-lit-double-layer', 'Return & Trim', 'return-trim', 'After Fabrication', 'after-fabrication', NULL, '[2,8]'),
('Dual Lit - Double Layer', 'dual-lit-double-layer', 'Face & Return', 'face-return', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Dual Lit - Double Layer', 'dual-lit-double-layer', 'Face & Return', 'face-return', 'After Cutting', 'after-cutting', NULL, '[2,3,6]'),
('Dual Lit - Double Layer', 'dual-lit-double-layer', 'Face & Return', 'face-return', 'After Bending', 'after-bending', NULL, NULL),
('Dual Lit - Double Layer', 'dual-lit-double-layer', 'Face & Return', 'face-return', 'After Fabrication', 'after-fabrication', NULL, '[2,8]'),
('Dual Lit - Double Layer', 'dual-lit-double-layer', 'Frame', 'frame', 'Before Cutting', 'before-cutting', NULL, NULL),
('Dual Lit - Double Layer', 'dual-lit-double-layer', 'Frame', 'frame', 'After Cutting', 'after-cutting', NULL, NULL),
('Dual Lit - Double Layer', 'dual-lit-double-layer', 'Frame', 'frame', 'After Bending', 'after-bending', NULL, NULL),
('Dual Lit - Double Layer', 'dual-lit-double-layer', 'Frame', 'frame', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Dual Lit - Double Layer', 'dual-lit-double-layer', 'All Sides', 'all-sides', 'Before Cutting', 'before-cutting', NULL, NULL),
('Dual Lit - Double Layer', 'dual-lit-double-layer', 'All Sides', 'all-sides', 'After Cutting', 'after-cutting', NULL, NULL),
('Dual Lit - Double Layer', 'dual-lit-double-layer', 'All Sides', 'all-sides', 'After Bending', 'after-bending', NULL, NULL),
('Dual Lit - Double Layer', 'dual-lit-double-layer', 'All Sides', 'all-sides', 'After Fabrication', 'after-fabrication', NULL, NULL),

-- Blade Sign
('Blade Sign', 'blade-sign', 'Face', 'face', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Blade Sign', 'blade-sign', 'Face', 'face', 'After Cutting', 'after-cutting', NULL, '[2,6]'),
('Blade Sign', 'blade-sign', 'Face', 'face', 'After Bending', 'after-bending', NULL, NULL),
('Blade Sign', 'blade-sign', 'Face', 'face', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Blade Sign', 'blade-sign', 'Return', 'return', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Blade Sign', 'blade-sign', 'Return', 'return', 'After Cutting', 'after-cutting', NULL, NULL),
('Blade Sign', 'blade-sign', 'Return', 'return', 'After Bending', 'after-bending', NULL, NULL),
('Blade Sign', 'blade-sign', 'Return', 'return', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Blade Sign', 'blade-sign', 'Trim', 'trim', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Blade Sign', 'blade-sign', 'Trim', 'trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Blade Sign', 'blade-sign', 'Trim', 'trim', 'After Bending', 'after-bending', NULL, NULL),
('Blade Sign', 'blade-sign', 'Trim', 'trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Blade Sign', 'blade-sign', 'Return & Trim', 'return-trim', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Blade Sign', 'blade-sign', 'Return & Trim', 'return-trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Blade Sign', 'blade-sign', 'Return & Trim', 'return-trim', 'After Bending', 'after-bending', NULL, NULL),
('Blade Sign', 'blade-sign', 'Return & Trim', 'return-trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Blade Sign', 'blade-sign', 'Face & Return', 'face-return', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Blade Sign', 'blade-sign', 'Face & Return', 'face-return', 'After Cutting', 'after-cutting', NULL, NULL),
('Blade Sign', 'blade-sign', 'Face & Return', 'face-return', 'After Bending', 'after-bending', NULL, NULL),
('Blade Sign', 'blade-sign', 'Face & Return', 'face-return', 'After Fabrication', 'after-fabrication', NULL, '[2,8]'),
('Blade Sign', 'blade-sign', 'Frame', 'frame', 'Before Cutting', 'before-cutting', NULL, NULL),
('Blade Sign', 'blade-sign', 'Frame', 'frame', 'After Cutting', 'after-cutting', NULL, NULL),
('Blade Sign', 'blade-sign', 'Frame', 'frame', 'After Bending', 'after-bending', NULL, NULL),
('Blade Sign', 'blade-sign', 'Frame', 'frame', 'After Fabrication', 'after-fabrication', NULL, '[8]'),
('Blade Sign', 'blade-sign', 'All Sides', 'all-sides', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Blade Sign', 'blade-sign', 'All Sides', 'all-sides', 'After Cutting', 'after-cutting', NULL, '[2,6]'),
('Blade Sign', 'blade-sign', 'All Sides', 'all-sides', 'After Bending', 'after-bending', NULL, NULL),
('Blade Sign', 'blade-sign', 'All Sides', 'all-sides', 'After Fabrication', 'after-fabrication', NULL, '[2,8]'),

-- Marquee Bulb
('Marquee Bulb', 'marquee-bulb', 'Face', 'face', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Marquee Bulb', 'marquee-bulb', 'Face', 'face', 'After Cutting', 'after-cutting', NULL, '[2,6]'),
('Marquee Bulb', 'marquee-bulb', 'Face', 'face', 'After Bending', 'after-bending', NULL, NULL),
('Marquee Bulb', 'marquee-bulb', 'Face', 'face', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Marquee Bulb', 'marquee-bulb', 'Return', 'return', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Marquee Bulb', 'marquee-bulb', 'Return', 'return', 'After Cutting', 'after-cutting', NULL, NULL),
('Marquee Bulb', 'marquee-bulb', 'Return', 'return', 'After Bending', 'after-bending', NULL, NULL),
('Marquee Bulb', 'marquee-bulb', 'Return', 'return', 'After Fabrication', 'after-fabrication', NULL, '[2,8]'),
('Marquee Bulb', 'marquee-bulb', 'Trim', 'trim', 'Before Cutting', 'before-cutting', NULL, NULL),
('Marquee Bulb', 'marquee-bulb', 'Trim', 'trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Marquee Bulb', 'marquee-bulb', 'Trim', 'trim', 'After Bending', 'after-bending', NULL, NULL),
('Marquee Bulb', 'marquee-bulb', 'Trim', 'trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Marquee Bulb', 'marquee-bulb', 'Return & Trim', 'return-trim', 'Before Cutting', 'before-cutting', NULL, NULL),
('Marquee Bulb', 'marquee-bulb', 'Return & Trim', 'return-trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Marquee Bulb', 'marquee-bulb', 'Return & Trim', 'return-trim', 'After Bending', 'after-bending', NULL, NULL),
('Marquee Bulb', 'marquee-bulb', 'Return & Trim', 'return-trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Marquee Bulb', 'marquee-bulb', 'Face & Return', 'face-return', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Marquee Bulb', 'marquee-bulb', 'Face & Return', 'face-return', 'After Cutting', 'after-cutting', NULL, NULL),
('Marquee Bulb', 'marquee-bulb', 'Face & Return', 'face-return', 'After Bending', 'after-bending', NULL, NULL),
('Marquee Bulb', 'marquee-bulb', 'Face & Return', 'face-return', 'After Fabrication', 'after-fabrication', NULL, '[2,8]'),
('Marquee Bulb', 'marquee-bulb', 'Frame', 'frame', 'Before Cutting', 'before-cutting', NULL, NULL),
('Marquee Bulb', 'marquee-bulb', 'Frame', 'frame', 'After Cutting', 'after-cutting', NULL, NULL),
('Marquee Bulb', 'marquee-bulb', 'Frame', 'frame', 'After Bending', 'after-bending', NULL, NULL),
('Marquee Bulb', 'marquee-bulb', 'Frame', 'frame', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Marquee Bulb', 'marquee-bulb', 'All Sides', 'all-sides', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Marquee Bulb', 'marquee-bulb', 'All Sides', 'all-sides', 'After Cutting', 'after-cutting', NULL, NULL),
('Marquee Bulb', 'marquee-bulb', 'All Sides', 'all-sides', 'After Bending', 'after-bending', NULL, NULL),
('Marquee Bulb', 'marquee-bulb', 'All Sides', 'all-sides', 'After Fabrication', 'after-fabrication', NULL, '[2,8]'),

-- Material Cut
('Material Cut', 'material-cut', 'Face', 'face', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Material Cut', 'material-cut', 'Face', 'face', 'After Cutting', 'after-cutting', NULL, '[5,6]'),
('Material Cut', 'material-cut', 'Face', 'face', 'After Bending', 'after-bending', NULL, NULL),
('Material Cut', 'material-cut', 'Face', 'face', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Material Cut', 'material-cut', 'Return', 'return', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Material Cut', 'material-cut', 'Return', 'return', 'After Cutting', 'after-cutting', NULL, NULL),
('Material Cut', 'material-cut', 'Return', 'return', 'After Bending', 'after-bending', NULL, NULL),
('Material Cut', 'material-cut', 'Return', 'return', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Material Cut', 'material-cut', 'Trim', 'trim', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Material Cut', 'material-cut', 'Trim', 'trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Material Cut', 'material-cut', 'Trim', 'trim', 'After Bending', 'after-bending', NULL, NULL),
('Material Cut', 'material-cut', 'Trim', 'trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Material Cut', 'material-cut', 'Return & Trim', 'return-trim', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Material Cut', 'material-cut', 'Return & Trim', 'return-trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Material Cut', 'material-cut', 'Return & Trim', 'return-trim', 'After Bending', 'after-bending', NULL, NULL),
('Material Cut', 'material-cut', 'Return & Trim', 'return-trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Material Cut', 'material-cut', 'Face & Return', 'face-return', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Material Cut', 'material-cut', 'Face & Return', 'face-return', 'After Cutting', 'after-cutting', NULL, '[2,3,5,6]'),
('Material Cut', 'material-cut', 'Face & Return', 'face-return', 'After Bending', 'after-bending', NULL, NULL),
('Material Cut', 'material-cut', 'Face & Return', 'face-return', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Material Cut', 'material-cut', 'Frame', 'frame', 'Before Cutting', 'before-cutting', NULL, NULL),
('Material Cut', 'material-cut', 'Frame', 'frame', 'After Cutting', 'after-cutting', NULL, NULL),
('Material Cut', 'material-cut', 'Frame', 'frame', 'After Bending', 'after-bending', NULL, NULL),
('Material Cut', 'material-cut', 'Frame', 'frame', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Material Cut', 'material-cut', 'All Sides', 'all-sides', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Material Cut', 'material-cut', 'All Sides', 'all-sides', 'After Cutting', 'after-cutting', NULL, NULL),
('Material Cut', 'material-cut', 'All Sides', 'all-sides', 'After Bending', 'after-bending', NULL, NULL),
('Material Cut', 'material-cut', 'All Sides', 'all-sides', 'After Fabrication', 'after-fabrication', NULL, NULL),

-- Return (P7, P2, NONE, NONE, P3, NONE, P7)
('Return', 'return', 'Face', 'face', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Return', 'return', 'Face', 'face', 'After Cutting', 'after-cutting', NULL, '[2,6]'),
('Return', 'return', 'Face', 'face', 'After Bending', 'after-bending', NULL, NULL),
('Return', 'return', 'Face', 'face', 'After Fabrication', 'after-fabrication', NULL, '[2,8]'),
('Return', 'return', 'Return', 'return', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Return', 'return', 'Return', 'return', 'After Cutting', 'after-cutting', NULL, NULL),
('Return', 'return', 'Return', 'return', 'After Bending', 'after-bending', NULL, NULL),
('Return', 'return', 'Return', 'return', 'After Fabrication', 'after-fabrication', NULL, '[2,8]'),
('Return', 'return', 'Trim', 'trim', 'Before Cutting', 'before-cutting', NULL, NULL),
('Return', 'return', 'Trim', 'trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Return', 'return', 'Trim', 'trim', 'After Bending', 'after-bending', NULL, NULL),
('Return', 'return', 'Trim', 'trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Return', 'return', 'Return & Trim', 'return-trim', 'Before Cutting', 'before-cutting', NULL, NULL),
('Return', 'return', 'Return & Trim', 'return-trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Return', 'return', 'Return & Trim', 'return-trim', 'After Bending', 'after-bending', NULL, NULL),
('Return', 'return', 'Return & Trim', 'return-trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Return', 'return', 'Face & Return', 'face-return', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Return', 'return', 'Face & Return', 'face-return', 'After Cutting', 'after-cutting', NULL, '[2,3,6]'),
('Return', 'return', 'Face & Return', 'face-return', 'After Bending', 'after-bending', NULL, NULL),
('Return', 'return', 'Face & Return', 'face-return', 'After Fabrication', 'after-fabrication', NULL, '[2,8]'),
('Return', 'return', 'Frame', 'frame', 'Before Cutting', 'before-cutting', NULL, NULL),
('Return', 'return', 'Frame', 'frame', 'After Cutting', 'after-cutting', NULL, NULL),
('Return', 'return', 'Frame', 'frame', 'After Bending', 'after-bending', NULL, NULL),
('Return', 'return', 'Frame', 'frame', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Return', 'return', 'All Sides', 'all-sides', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Return', 'return', 'All Sides', 'all-sides', 'After Cutting', 'after-cutting', NULL, '[2,6]'),
('Return', 'return', 'All Sides', 'all-sides', 'After Bending', 'after-bending', NULL, NULL),
('Return', 'return', 'All Sides', 'all-sides', 'After Fabrication', 'after-fabrication', NULL, '[2,8]'),

-- Trim Cap (P7, NONE, [[2,3], N, N, [2,8]], NONE, P7, NONE, P7)
('Trim Cap', 'trim-cap', 'Face', 'face', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Trim Cap', 'trim-cap', 'Face', 'face', 'After Cutting', 'after-cutting', NULL, '[2,6]'),
('Trim Cap', 'trim-cap', 'Face', 'face', 'After Bending', 'after-bending', NULL, NULL),
('Trim Cap', 'trim-cap', 'Face', 'face', 'After Fabrication', 'after-fabrication', NULL, '[2,8]'),
('Trim Cap', 'trim-cap', 'Return', 'return', 'Before Cutting', 'before-cutting', NULL, NULL),
('Trim Cap', 'trim-cap', 'Return', 'return', 'After Cutting', 'after-cutting', NULL, NULL),
('Trim Cap', 'trim-cap', 'Return', 'return', 'After Bending', 'after-bending', NULL, NULL),
('Trim Cap', 'trim-cap', 'Return', 'return', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Trim Cap', 'trim-cap', 'Trim', 'trim', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Trim Cap', 'trim-cap', 'Trim', 'trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Trim Cap', 'trim-cap', 'Trim', 'trim', 'After Bending', 'after-bending', NULL, NULL),
('Trim Cap', 'trim-cap', 'Trim', 'trim', 'After Fabrication', 'after-fabrication', NULL, '[2,8]'),
('Trim Cap', 'trim-cap', 'Return & Trim', 'return-trim', 'Before Cutting', 'before-cutting', NULL, NULL),
('Trim Cap', 'trim-cap', 'Return & Trim', 'return-trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Trim Cap', 'trim-cap', 'Return & Trim', 'return-trim', 'After Bending', 'after-bending', NULL, NULL),
('Trim Cap', 'trim-cap', 'Return & Trim', 'return-trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Trim Cap', 'trim-cap', 'Face & Return', 'face-return', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Trim Cap', 'trim-cap', 'Face & Return', 'face-return', 'After Cutting', 'after-cutting', NULL, '[2,6]'),
('Trim Cap', 'trim-cap', 'Face & Return', 'face-return', 'After Bending', 'after-bending', NULL, NULL),
('Trim Cap', 'trim-cap', 'Face & Return', 'face-return', 'After Fabrication', 'after-fabrication', NULL, '[2,8]'),
('Trim Cap', 'trim-cap', 'Frame', 'frame', 'Before Cutting', 'before-cutting', NULL, NULL),
('Trim Cap', 'trim-cap', 'Frame', 'frame', 'After Cutting', 'after-cutting', NULL, NULL),
('Trim Cap', 'trim-cap', 'Frame', 'frame', 'After Bending', 'after-bending', NULL, NULL),
('Trim Cap', 'trim-cap', 'Frame', 'frame', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Trim Cap', 'trim-cap', 'All Sides', 'all-sides', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Trim Cap', 'trim-cap', 'All Sides', 'all-sides', 'After Cutting', 'after-cutting', NULL, '[2,6]'),
('Trim Cap', 'trim-cap', 'All Sides', 'all-sides', 'After Bending', 'after-bending', NULL, NULL),
('Trim Cap', 'trim-cap', 'All Sides', 'all-sides', 'After Fabrication', 'after-fabrication', NULL, '[2,8]'),

-- 3D Print
('3D Print', '3d-print', 'Face', 'face', 'Before Cutting', 'before-cutting', NULL, '[3]'),
('3D Print', '3d-print', 'Face', 'face', 'After Cutting', 'after-cutting', NULL, '[6]'),
('3D Print', '3d-print', 'Face', 'face', 'After Bending', 'after-bending', NULL, NULL),
('3D Print', '3d-print', 'Face', 'face', 'After Fabrication', 'after-fabrication', NULL, NULL),
('3D Print', '3d-print', 'Return', 'return', 'Before Cutting', 'before-cutting', NULL, NULL),
('3D Print', '3d-print', 'Return', 'return', 'After Cutting', 'after-cutting', NULL, NULL),
('3D Print', '3d-print', 'Return', 'return', 'After Bending', 'after-bending', NULL, NULL),
('3D Print', '3d-print', 'Return', 'return', 'After Fabrication', 'after-fabrication', NULL, '[8]'),
('3D Print', '3d-print', 'Trim', 'trim', 'Before Cutting', 'before-cutting', NULL, NULL),
('3D Print', '3d-print', 'Trim', 'trim', 'After Cutting', 'after-cutting', NULL, NULL),
('3D Print', '3d-print', 'Trim', 'trim', 'After Bending', 'after-bending', NULL, NULL),
('3D Print', '3d-print', 'Trim', 'trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('3D Print', '3d-print', 'Return & Trim', 'return-trim', 'Before Cutting', 'before-cutting', NULL, NULL),
('3D Print', '3d-print', 'Return & Trim', 'return-trim', 'After Cutting', 'after-cutting', NULL, NULL),
('3D Print', '3d-print', 'Return & Trim', 'return-trim', 'After Bending', 'after-bending', NULL, NULL),
('3D Print', '3d-print', 'Return & Trim', 'return-trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('3D Print', '3d-print', 'Face & Return', 'face-return', 'Before Cutting', 'before-cutting', NULL, '[3]'),
('3D Print', '3d-print', 'Face & Return', 'face-return', 'After Cutting', 'after-cutting', NULL, '[6]'),
('3D Print', '3d-print', 'Face & Return', 'face-return', 'After Bending', 'after-bending', NULL, NULL),
('3D Print', '3d-print', 'Face & Return', 'face-return', 'After Fabrication', 'after-fabrication', NULL, '[8]'),
('3D Print', '3d-print', 'Frame', 'frame', 'Before Cutting', 'before-cutting', NULL, NULL),
('3D Print', '3d-print', 'Frame', 'frame', 'After Cutting', 'after-cutting', NULL, NULL),
('3D Print', '3d-print', 'Frame', 'frame', 'After Bending', 'after-bending', NULL, NULL),
('3D Print', '3d-print', 'Frame', 'frame', 'After Fabrication', 'after-fabrication', NULL, NULL),
('3D Print', '3d-print', 'All Sides', 'all-sides', 'Before Cutting', 'before-cutting', NULL, NULL),
('3D Print', '3d-print', 'All Sides', 'all-sides', 'After Cutting', 'after-cutting', NULL, NULL),
('3D Print', '3d-print', 'All Sides', 'all-sides', 'After Bending', 'after-bending', NULL, NULL),
('3D Print', '3d-print', 'All Sides', 'all-sides', 'After Fabrication', 'after-fabrication', NULL, '[8]'),

-- Frame (P6 pattern: [[1,3], [4,6], N, [4,8]])
('Frame', 'frame', 'Face', 'face', 'Before Cutting', 'before-cutting', NULL, '[1,3]'),
('Frame', 'frame', 'Face', 'face', 'After Cutting', 'after-cutting', NULL, '[4,6]'),
('Frame', 'frame', 'Face', 'face', 'After Bending', 'after-bending', NULL, NULL),
('Frame', 'frame', 'Face', 'face', 'After Fabrication', 'after-fabrication', NULL, '[4,8]'),
('Frame', 'frame', 'Return', 'return', 'Before Cutting', 'before-cutting', NULL, '[1,3]'),
('Frame', 'frame', 'Return', 'return', 'After Cutting', 'after-cutting', NULL, '[4,6]'),
('Frame', 'frame', 'Return', 'return', 'After Bending', 'after-bending', NULL, NULL),
('Frame', 'frame', 'Return', 'return', 'After Fabrication', 'after-fabrication', NULL, '[4,8]'),
('Frame', 'frame', 'Trim', 'trim', 'Before Cutting', 'before-cutting', NULL, NULL),
('Frame', 'frame', 'Trim', 'trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Frame', 'frame', 'Trim', 'trim', 'After Bending', 'after-bending', NULL, NULL),
('Frame', 'frame', 'Trim', 'trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Frame', 'frame', 'Return & Trim', 'return-trim', 'Before Cutting', 'before-cutting', NULL, NULL),
('Frame', 'frame', 'Return & Trim', 'return-trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Frame', 'frame', 'Return & Trim', 'return-trim', 'After Bending', 'after-bending', NULL, NULL),
('Frame', 'frame', 'Return & Trim', 'return-trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Frame', 'frame', 'Face & Return', 'face-return', 'Before Cutting', 'before-cutting', NULL, '[1,3]'),
('Frame', 'frame', 'Face & Return', 'face-return', 'After Cutting', 'after-cutting', NULL, '[4,6]'),
('Frame', 'frame', 'Face & Return', 'face-return', 'After Bending', 'after-bending', NULL, NULL),
('Frame', 'frame', 'Face & Return', 'face-return', 'After Fabrication', 'after-fabrication', NULL, '[4,8]'),
('Frame', 'frame', 'Frame', 'frame', 'Before Cutting', 'before-cutting', NULL, '[1,3]'),
('Frame', 'frame', 'Frame', 'frame', 'After Cutting', 'after-cutting', NULL, '[4,6]'),
('Frame', 'frame', 'Frame', 'frame', 'After Bending', 'after-bending', NULL, NULL),
('Frame', 'frame', 'Frame', 'frame', 'After Fabrication', 'after-fabrication', NULL, '[4,8]'),
('Frame', 'frame', 'All Sides', 'all-sides', 'Before Cutting', 'before-cutting', NULL, '[1,3]'),
('Frame', 'frame', 'All Sides', 'all-sides', 'After Cutting', 'after-cutting', NULL, '[4,6]'),
('Frame', 'frame', 'All Sides', 'all-sides', 'After Bending', 'after-bending', NULL, NULL),
('Frame', 'frame', 'All Sides', 'all-sides', 'After Fabrication', 'after-fabrication', NULL, '[4,8]'),

-- Aluminum Raceway (P4 pattern: [[2,3], [5,6], [5,7], [5,8]])
('Aluminum Raceway', 'aluminum-raceway', 'Face', 'face', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Aluminum Raceway', 'aluminum-raceway', 'Face', 'face', 'After Cutting', 'after-cutting', NULL, '[5,6]'),
('Aluminum Raceway', 'aluminum-raceway', 'Face', 'face', 'After Bending', 'after-bending', NULL, '[5,7]'),
('Aluminum Raceway', 'aluminum-raceway', 'Face', 'face', 'After Fabrication', 'after-fabrication', NULL, '[5,8]'),
('Aluminum Raceway', 'aluminum-raceway', 'Return', 'return', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Aluminum Raceway', 'aluminum-raceway', 'Return', 'return', 'After Cutting', 'after-cutting', NULL, '[5,6]'),
('Aluminum Raceway', 'aluminum-raceway', 'Return', 'return', 'After Bending', 'after-bending', NULL, '[5,7]'),
('Aluminum Raceway', 'aluminum-raceway', 'Return', 'return', 'After Fabrication', 'after-fabrication', NULL, '[5,8]'),
('Aluminum Raceway', 'aluminum-raceway', 'Trim', 'trim', 'Before Cutting', 'before-cutting', NULL, NULL),
('Aluminum Raceway', 'aluminum-raceway', 'Trim', 'trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Aluminum Raceway', 'aluminum-raceway', 'Trim', 'trim', 'After Bending', 'after-bending', NULL, NULL),
('Aluminum Raceway', 'aluminum-raceway', 'Trim', 'trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Aluminum Raceway', 'aluminum-raceway', 'Return & Trim', 'return-trim', 'Before Cutting', 'before-cutting', NULL, NULL),
('Aluminum Raceway', 'aluminum-raceway', 'Return & Trim', 'return-trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Aluminum Raceway', 'aluminum-raceway', 'Return & Trim', 'return-trim', 'After Bending', 'after-bending', NULL, NULL),
('Aluminum Raceway', 'aluminum-raceway', 'Return & Trim', 'return-trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Aluminum Raceway', 'aluminum-raceway', 'Face & Return', 'face-return', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Aluminum Raceway', 'aluminum-raceway', 'Face & Return', 'face-return', 'After Cutting', 'after-cutting', NULL, '[5,6]'),
('Aluminum Raceway', 'aluminum-raceway', 'Face & Return', 'face-return', 'After Bending', 'after-bending', NULL, '[5,7]'),
('Aluminum Raceway', 'aluminum-raceway', 'Face & Return', 'face-return', 'After Fabrication', 'after-fabrication', NULL, '[5,8]'),
('Aluminum Raceway', 'aluminum-raceway', 'Frame', 'frame', 'Before Cutting', 'before-cutting', NULL, NULL),
('Aluminum Raceway', 'aluminum-raceway', 'Frame', 'frame', 'After Cutting', 'after-cutting', NULL, NULL),
('Aluminum Raceway', 'aluminum-raceway', 'Frame', 'frame', 'After Bending', 'after-bending', NULL, NULL),
('Aluminum Raceway', 'aluminum-raceway', 'Frame', 'frame', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Aluminum Raceway', 'aluminum-raceway', 'All Sides', 'all-sides', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Aluminum Raceway', 'aluminum-raceway', 'All Sides', 'all-sides', 'After Cutting', 'after-cutting', NULL, '[5,6]'),
('Aluminum Raceway', 'aluminum-raceway', 'All Sides', 'all-sides', 'After Bending', 'after-bending', NULL, '[5,7]'),
('Aluminum Raceway', 'aluminum-raceway', 'All Sides', 'all-sides', 'After Fabrication', 'after-fabrication', NULL, '[5,8]'),

-- Extrusion Raceway (same as Aluminum Raceway)
('Extrusion Raceway', 'extrusion-raceway', 'Face', 'face', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Extrusion Raceway', 'extrusion-raceway', 'Face', 'face', 'After Cutting', 'after-cutting', NULL, '[5,6]'),
('Extrusion Raceway', 'extrusion-raceway', 'Face', 'face', 'After Bending', 'after-bending', NULL, '[5,7]'),
('Extrusion Raceway', 'extrusion-raceway', 'Face', 'face', 'After Fabrication', 'after-fabrication', NULL, '[5,8]'),
('Extrusion Raceway', 'extrusion-raceway', 'Return', 'return', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Extrusion Raceway', 'extrusion-raceway', 'Return', 'return', 'After Cutting', 'after-cutting', NULL, '[5,6]'),
('Extrusion Raceway', 'extrusion-raceway', 'Return', 'return', 'After Bending', 'after-bending', NULL, '[5,7]'),
('Extrusion Raceway', 'extrusion-raceway', 'Return', 'return', 'After Fabrication', 'after-fabrication', NULL, '[5,8]'),
('Extrusion Raceway', 'extrusion-raceway', 'Trim', 'trim', 'Before Cutting', 'before-cutting', NULL, NULL),
('Extrusion Raceway', 'extrusion-raceway', 'Trim', 'trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Extrusion Raceway', 'extrusion-raceway', 'Trim', 'trim', 'After Bending', 'after-bending', NULL, NULL),
('Extrusion Raceway', 'extrusion-raceway', 'Trim', 'trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Extrusion Raceway', 'extrusion-raceway', 'Return & Trim', 'return-trim', 'Before Cutting', 'before-cutting', NULL, NULL),
('Extrusion Raceway', 'extrusion-raceway', 'Return & Trim', 'return-trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Extrusion Raceway', 'extrusion-raceway', 'Return & Trim', 'return-trim', 'After Bending', 'after-bending', NULL, NULL),
('Extrusion Raceway', 'extrusion-raceway', 'Return & Trim', 'return-trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Extrusion Raceway', 'extrusion-raceway', 'Face & Return', 'face-return', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Extrusion Raceway', 'extrusion-raceway', 'Face & Return', 'face-return', 'After Cutting', 'after-cutting', NULL, '[5,6]'),
('Extrusion Raceway', 'extrusion-raceway', 'Face & Return', 'face-return', 'After Bending', 'after-bending', NULL, '[5,7]'),
('Extrusion Raceway', 'extrusion-raceway', 'Face & Return', 'face-return', 'After Fabrication', 'after-fabrication', NULL, '[5,8]'),
('Extrusion Raceway', 'extrusion-raceway', 'Frame', 'frame', 'Before Cutting', 'before-cutting', NULL, NULL),
('Extrusion Raceway', 'extrusion-raceway', 'Frame', 'frame', 'After Cutting', 'after-cutting', NULL, NULL),
('Extrusion Raceway', 'extrusion-raceway', 'Frame', 'frame', 'After Bending', 'after-bending', NULL, NULL),
('Extrusion Raceway', 'extrusion-raceway', 'Frame', 'frame', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Extrusion Raceway', 'extrusion-raceway', 'All Sides', 'all-sides', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Extrusion Raceway', 'extrusion-raceway', 'All Sides', 'all-sides', 'After Cutting', 'after-cutting', NULL, '[5,6]'),
('Extrusion Raceway', 'extrusion-raceway', 'All Sides', 'all-sides', 'After Bending', 'after-bending', NULL, '[5,7]'),
('Extrusion Raceway', 'extrusion-raceway', 'All Sides', 'all-sides', 'After Fabrication', 'after-fabrication', NULL, '[5,8]'),

-- Push Thru (Face: [[2,3], [5,6], [5,7], [5,8]], Return+: P5 pattern [[1,3], [4,6], [4,7], [4,8]])
('Push Thru', 'push-thru', 'Face', 'face', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Push Thru', 'push-thru', 'Face', 'face', 'After Cutting', 'after-cutting', NULL, '[5,6]'),
('Push Thru', 'push-thru', 'Face', 'face', 'After Bending', 'after-bending', NULL, '[5,7]'),
('Push Thru', 'push-thru', 'Face', 'face', 'After Fabrication', 'after-fabrication', NULL, '[5,8]'),
('Push Thru', 'push-thru', 'Return', 'return', 'Before Cutting', 'before-cutting', NULL, '[1,3]'),
('Push Thru', 'push-thru', 'Return', 'return', 'After Cutting', 'after-cutting', NULL, '[4,6]'),
('Push Thru', 'push-thru', 'Return', 'return', 'After Bending', 'after-bending', NULL, '[4,7]'),
('Push Thru', 'push-thru', 'Return', 'return', 'After Fabrication', 'after-fabrication', NULL, '[4,8]'),
('Push Thru', 'push-thru', 'Trim', 'trim', 'Before Cutting', 'before-cutting', NULL, NULL),
('Push Thru', 'push-thru', 'Trim', 'trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Push Thru', 'push-thru', 'Trim', 'trim', 'After Bending', 'after-bending', NULL, NULL),
('Push Thru', 'push-thru', 'Trim', 'trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Push Thru', 'push-thru', 'Return & Trim', 'return-trim', 'Before Cutting', 'before-cutting', NULL, NULL),
('Push Thru', 'push-thru', 'Return & Trim', 'return-trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Push Thru', 'push-thru', 'Return & Trim', 'return-trim', 'After Bending', 'after-bending', NULL, NULL),
('Push Thru', 'push-thru', 'Return & Trim', 'return-trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Push Thru', 'push-thru', 'Face & Return', 'face-return', 'Before Cutting', 'before-cutting', NULL, '[1,3]'),
('Push Thru', 'push-thru', 'Face & Return', 'face-return', 'After Cutting', 'after-cutting', NULL, '[4,6]'),
('Push Thru', 'push-thru', 'Face & Return', 'face-return', 'After Bending', 'after-bending', NULL, '[4,7]'),
('Push Thru', 'push-thru', 'Face & Return', 'face-return', 'After Fabrication', 'after-fabrication', NULL, '[4,8]'),
('Push Thru', 'push-thru', 'Frame', 'frame', 'Before Cutting', 'before-cutting', NULL, NULL),
('Push Thru', 'push-thru', 'Frame', 'frame', 'After Cutting', 'after-cutting', NULL, NULL),
('Push Thru', 'push-thru', 'Frame', 'frame', 'After Bending', 'after-bending', NULL, NULL),
('Push Thru', 'push-thru', 'Frame', 'frame', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Push Thru', 'push-thru', 'All Sides', 'all-sides', 'Before Cutting', 'before-cutting', NULL, '[1,3]'),
('Push Thru', 'push-thru', 'All Sides', 'all-sides', 'After Cutting', 'after-cutting', NULL, '[4,6]'),
('Push Thru', 'push-thru', 'All Sides', 'all-sides', 'After Bending', 'after-bending', NULL, '[4,7]'),
('Push Thru', 'push-thru', 'All Sides', 'all-sides', 'After Fabrication', 'after-fabrication', NULL, '[4,8]'),

-- Knockout Box (same as Push Thru)
('Knockout Box', 'knockout-box', 'Face', 'face', 'Before Cutting', 'before-cutting', NULL, '[2,3]'),
('Knockout Box', 'knockout-box', 'Face', 'face', 'After Cutting', 'after-cutting', NULL, '[5,6]'),
('Knockout Box', 'knockout-box', 'Face', 'face', 'After Bending', 'after-bending', NULL, '[5,7]'),
('Knockout Box', 'knockout-box', 'Face', 'face', 'After Fabrication', 'after-fabrication', NULL, '[5,8]'),
('Knockout Box', 'knockout-box', 'Return', 'return', 'Before Cutting', 'before-cutting', NULL, '[1,3]'),
('Knockout Box', 'knockout-box', 'Return', 'return', 'After Cutting', 'after-cutting', NULL, '[4,6]'),
('Knockout Box', 'knockout-box', 'Return', 'return', 'After Bending', 'after-bending', NULL, '[4,7]'),
('Knockout Box', 'knockout-box', 'Return', 'return', 'After Fabrication', 'after-fabrication', NULL, '[4,8]'),
('Knockout Box', 'knockout-box', 'Trim', 'trim', 'Before Cutting', 'before-cutting', NULL, NULL),
('Knockout Box', 'knockout-box', 'Trim', 'trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Knockout Box', 'knockout-box', 'Trim', 'trim', 'After Bending', 'after-bending', NULL, NULL),
('Knockout Box', 'knockout-box', 'Trim', 'trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Knockout Box', 'knockout-box', 'Return & Trim', 'return-trim', 'Before Cutting', 'before-cutting', NULL, NULL),
('Knockout Box', 'knockout-box', 'Return & Trim', 'return-trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Knockout Box', 'knockout-box', 'Return & Trim', 'return-trim', 'After Bending', 'after-bending', NULL, NULL),
('Knockout Box', 'knockout-box', 'Return & Trim', 'return-trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Knockout Box', 'knockout-box', 'Face & Return', 'face-return', 'Before Cutting', 'before-cutting', NULL, '[1,3]'),
('Knockout Box', 'knockout-box', 'Face & Return', 'face-return', 'After Cutting', 'after-cutting', NULL, '[4,6]'),
('Knockout Box', 'knockout-box', 'Face & Return', 'face-return', 'After Bending', 'after-bending', NULL, '[4,7]'),
('Knockout Box', 'knockout-box', 'Face & Return', 'face-return', 'After Fabrication', 'after-fabrication', NULL, '[4,8]'),
('Knockout Box', 'knockout-box', 'Frame', 'frame', 'Before Cutting', 'before-cutting', NULL, NULL),
('Knockout Box', 'knockout-box', 'Frame', 'frame', 'After Cutting', 'after-cutting', NULL, NULL),
('Knockout Box', 'knockout-box', 'Frame', 'frame', 'After Bending', 'after-bending', NULL, NULL),
('Knockout Box', 'knockout-box', 'Frame', 'frame', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Knockout Box', 'knockout-box', 'All Sides', 'all-sides', 'Before Cutting', 'before-cutting', NULL, '[1,3]'),
('Knockout Box', 'knockout-box', 'All Sides', 'all-sides', 'After Cutting', 'after-cutting', NULL, '[4,6]'),
('Knockout Box', 'knockout-box', 'All Sides', 'all-sides', 'After Bending', 'after-bending', NULL, '[4,7]'),
('Knockout Box', 'knockout-box', 'All Sides', 'all-sides', 'After Fabrication', 'after-fabrication', NULL, '[4,8]'),

-- Neon LED
('Neon LED', 'neon-led', 'Face', 'face', 'Before Cutting', 'before-cutting', NULL, '[3]'),
('Neon LED', 'neon-led', 'Face', 'face', 'After Cutting', 'after-cutting', NULL, '[6]'),
('Neon LED', 'neon-led', 'Face', 'face', 'After Bending', 'after-bending', NULL, NULL),
('Neon LED', 'neon-led', 'Face', 'face', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Neon LED', 'neon-led', 'Return', 'return', 'Before Cutting', 'before-cutting', NULL, NULL),
('Neon LED', 'neon-led', 'Return', 'return', 'After Cutting', 'after-cutting', NULL, '[6]'),
('Neon LED', 'neon-led', 'Return', 'return', 'After Bending', 'after-bending', NULL, NULL),
('Neon LED', 'neon-led', 'Return', 'return', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Neon LED', 'neon-led', 'Trim', 'trim', 'Before Cutting', 'before-cutting', NULL, NULL),
('Neon LED', 'neon-led', 'Trim', 'trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Neon LED', 'neon-led', 'Trim', 'trim', 'After Bending', 'after-bending', NULL, NULL),
('Neon LED', 'neon-led', 'Trim', 'trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Neon LED', 'neon-led', 'Return & Trim', 'return-trim', 'Before Cutting', 'before-cutting', NULL, NULL),
('Neon LED', 'neon-led', 'Return & Trim', 'return-trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Neon LED', 'neon-led', 'Return & Trim', 'return-trim', 'After Bending', 'after-bending', NULL, NULL),
('Neon LED', 'neon-led', 'Return & Trim', 'return-trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Neon LED', 'neon-led', 'Face & Return', 'face-return', 'Before Cutting', 'before-cutting', NULL, NULL),
('Neon LED', 'neon-led', 'Face & Return', 'face-return', 'After Cutting', 'after-cutting', NULL, '[6]'),
('Neon LED', 'neon-led', 'Face & Return', 'face-return', 'After Bending', 'after-bending', NULL, NULL),
('Neon LED', 'neon-led', 'Face & Return', 'face-return', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Neon LED', 'neon-led', 'Frame', 'frame', 'Before Cutting', 'before-cutting', NULL, NULL),
('Neon LED', 'neon-led', 'Frame', 'frame', 'After Cutting', 'after-cutting', NULL, NULL),
('Neon LED', 'neon-led', 'Frame', 'frame', 'After Bending', 'after-bending', NULL, NULL),
('Neon LED', 'neon-led', 'Frame', 'frame', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Neon LED', 'neon-led', 'All Sides', 'all-sides', 'Before Cutting', 'before-cutting', NULL, NULL),
('Neon LED', 'neon-led', 'All Sides', 'all-sides', 'After Cutting', 'after-cutting', NULL, '[6]'),
('Neon LED', 'neon-led', 'All Sides', 'all-sides', 'After Bending', 'after-bending', NULL, NULL),
('Neon LED', 'neon-led', 'All Sides', 'all-sides', 'After Fabrication', 'after-fabrication', NULL, NULL),

-- Painting (all NONE - intentionally empty, requires manual tasks)
('Painting', 'painting', 'Face', 'face', 'Before Cutting', 'before-cutting', NULL, NULL),
('Painting', 'painting', 'Face', 'face', 'After Cutting', 'after-cutting', NULL, NULL),
('Painting', 'painting', 'Face', 'face', 'After Bending', 'after-bending', NULL, NULL),
('Painting', 'painting', 'Face', 'face', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Painting', 'painting', 'Return', 'return', 'Before Cutting', 'before-cutting', NULL, NULL),
('Painting', 'painting', 'Return', 'return', 'After Cutting', 'after-cutting', NULL, NULL),
('Painting', 'painting', 'Return', 'return', 'After Bending', 'after-bending', NULL, NULL),
('Painting', 'painting', 'Return', 'return', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Painting', 'painting', 'Trim', 'trim', 'Before Cutting', 'before-cutting', NULL, NULL),
('Painting', 'painting', 'Trim', 'trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Painting', 'painting', 'Trim', 'trim', 'After Bending', 'after-bending', NULL, NULL),
('Painting', 'painting', 'Trim', 'trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Painting', 'painting', 'Return & Trim', 'return-trim', 'Before Cutting', 'before-cutting', NULL, NULL),
('Painting', 'painting', 'Return & Trim', 'return-trim', 'After Cutting', 'after-cutting', NULL, NULL),
('Painting', 'painting', 'Return & Trim', 'return-trim', 'After Bending', 'after-bending', NULL, NULL),
('Painting', 'painting', 'Return & Trim', 'return-trim', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Painting', 'painting', 'Face & Return', 'face-return', 'Before Cutting', 'before-cutting', NULL, NULL),
('Painting', 'painting', 'Face & Return', 'face-return', 'After Cutting', 'after-cutting', NULL, NULL),
('Painting', 'painting', 'Face & Return', 'face-return', 'After Bending', 'after-bending', NULL, NULL),
('Painting', 'painting', 'Face & Return', 'face-return', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Painting', 'painting', 'Frame', 'frame', 'Before Cutting', 'before-cutting', NULL, NULL),
('Painting', 'painting', 'Frame', 'frame', 'After Cutting', 'after-cutting', NULL, NULL),
('Painting', 'painting', 'Frame', 'frame', 'After Bending', 'after-bending', NULL, NULL),
('Painting', 'painting', 'Frame', 'frame', 'After Fabrication', 'after-fabrication', NULL, NULL),
('Painting', 'painting', 'All Sides', 'all-sides', 'Before Cutting', 'before-cutting', NULL, NULL),
('Painting', 'painting', 'All Sides', 'all-sides', 'After Cutting', 'after-cutting', NULL, NULL),
('Painting', 'painting', 'All Sides', 'all-sides', 'After Bending', 'after-bending', NULL, NULL),
('Painting', 'painting', 'All Sides', 'all-sides', 'After Fabrication', 'after-fabrication', NULL, NULL),

-- =============================================================================
-- Substrate Cut - Metal variant
-- =============================================================================
('Substrate Cut', 'substrate-cut', 'Face', 'face', 'Before Cutting', 'before-cutting', 'metal', '[2,3]'),
('Substrate Cut', 'substrate-cut', 'Face', 'face', 'After Cutting', 'after-cutting', 'metal', '[2,6]'),
('Substrate Cut', 'substrate-cut', 'Face', 'face', 'After Bending', 'after-bending', 'metal', '[1,8]'),
('Substrate Cut', 'substrate-cut', 'Face', 'face', 'After Fabrication', 'after-fabrication', 'metal', '[1,8]'),
('Substrate Cut', 'substrate-cut', 'Return', 'return', 'Before Cutting', 'before-cutting', 'metal', NULL),
('Substrate Cut', 'substrate-cut', 'Return', 'return', 'After Cutting', 'after-cutting', 'metal', NULL),
('Substrate Cut', 'substrate-cut', 'Return', 'return', 'After Bending', 'after-bending', 'metal', NULL),
('Substrate Cut', 'substrate-cut', 'Return', 'return', 'After Fabrication', 'after-fabrication', 'metal', NULL),
('Substrate Cut', 'substrate-cut', 'Trim', 'trim', 'Before Cutting', 'before-cutting', 'metal', NULL),
('Substrate Cut', 'substrate-cut', 'Trim', 'trim', 'After Cutting', 'after-cutting', 'metal', NULL),
('Substrate Cut', 'substrate-cut', 'Trim', 'trim', 'After Bending', 'after-bending', 'metal', NULL),
('Substrate Cut', 'substrate-cut', 'Trim', 'trim', 'After Fabrication', 'after-fabrication', 'metal', NULL),
('Substrate Cut', 'substrate-cut', 'Return & Trim', 'return-trim', 'Before Cutting', 'before-cutting', 'metal', NULL),
('Substrate Cut', 'substrate-cut', 'Return & Trim', 'return-trim', 'After Cutting', 'after-cutting', 'metal', NULL),
('Substrate Cut', 'substrate-cut', 'Return & Trim', 'return-trim', 'After Bending', 'after-bending', 'metal', NULL),
('Substrate Cut', 'substrate-cut', 'Return & Trim', 'return-trim', 'After Fabrication', 'after-fabrication', 'metal', NULL),
('Substrate Cut', 'substrate-cut', 'Face & Return', 'face-return', 'Before Cutting', 'before-cutting', 'metal', NULL),
('Substrate Cut', 'substrate-cut', 'Face & Return', 'face-return', 'After Cutting', 'after-cutting', 'metal', '[1,6]'),
('Substrate Cut', 'substrate-cut', 'Face & Return', 'face-return', 'After Bending', 'after-bending', 'metal', '[2,6]'),
('Substrate Cut', 'substrate-cut', 'Face & Return', 'face-return', 'After Fabrication', 'after-fabrication', 'metal', '[2,8]'),
('Substrate Cut', 'substrate-cut', 'Frame', 'frame', 'Before Cutting', 'before-cutting', 'metal', NULL),
('Substrate Cut', 'substrate-cut', 'Frame', 'frame', 'After Cutting', 'after-cutting', 'metal', NULL),
('Substrate Cut', 'substrate-cut', 'Frame', 'frame', 'After Bending', 'after-bending', 'metal', NULL),
('Substrate Cut', 'substrate-cut', 'Frame', 'frame', 'After Fabrication', 'after-fabrication', 'metal', NULL),
('Substrate Cut', 'substrate-cut', 'All Sides', 'all-sides', 'Before Cutting', 'before-cutting', 'metal', NULL),
('Substrate Cut', 'substrate-cut', 'All Sides', 'all-sides', 'After Cutting', 'after-cutting', 'metal', '[4,6]'),
('Substrate Cut', 'substrate-cut', 'All Sides', 'all-sides', 'After Bending', 'after-bending', 'metal', '[4,7]'),
('Substrate Cut', 'substrate-cut', 'All Sides', 'all-sides', 'After Fabrication', 'after-fabrication', 'metal', '[4,8]'),

-- =============================================================================
-- Substrate Cut - Plastic variant
-- =============================================================================
('Substrate Cut', 'substrate-cut', 'Face', 'face', 'Before Cutting', 'before-cutting', 'plastic', '[3]'),
('Substrate Cut', 'substrate-cut', 'Face', 'face', 'After Cutting', 'after-cutting', 'plastic', '[6]'),
('Substrate Cut', 'substrate-cut', 'Face', 'face', 'After Bending', 'after-bending', 'plastic', NULL),
('Substrate Cut', 'substrate-cut', 'Face', 'face', 'After Fabrication', 'after-fabrication', 'plastic', '[8]'),
('Substrate Cut', 'substrate-cut', 'Return', 'return', 'Before Cutting', 'before-cutting', 'plastic', NULL),
('Substrate Cut', 'substrate-cut', 'Return', 'return', 'After Cutting', 'after-cutting', 'plastic', '[6]'),
('Substrate Cut', 'substrate-cut', 'Return', 'return', 'After Bending', 'after-bending', 'plastic', NULL),
('Substrate Cut', 'substrate-cut', 'Return', 'return', 'After Fabrication', 'after-fabrication', 'plastic', '[8]'),
('Substrate Cut', 'substrate-cut', 'Trim', 'trim', 'Before Cutting', 'before-cutting', 'plastic', NULL),
('Substrate Cut', 'substrate-cut', 'Trim', 'trim', 'After Cutting', 'after-cutting', 'plastic', NULL),
('Substrate Cut', 'substrate-cut', 'Trim', 'trim', 'After Bending', 'after-bending', 'plastic', NULL),
('Substrate Cut', 'substrate-cut', 'Trim', 'trim', 'After Fabrication', 'after-fabrication', 'plastic', NULL),
('Substrate Cut', 'substrate-cut', 'Return & Trim', 'return-trim', 'Before Cutting', 'before-cutting', 'plastic', NULL),
('Substrate Cut', 'substrate-cut', 'Return & Trim', 'return-trim', 'After Cutting', 'after-cutting', 'plastic', NULL),
('Substrate Cut', 'substrate-cut', 'Return & Trim', 'return-trim', 'After Bending', 'after-bending', 'plastic', NULL),
('Substrate Cut', 'substrate-cut', 'Return & Trim', 'return-trim', 'After Fabrication', 'after-fabrication', 'plastic', NULL),
('Substrate Cut', 'substrate-cut', 'Face & Return', 'face-return', 'Before Cutting', 'before-cutting', 'plastic', NULL),
('Substrate Cut', 'substrate-cut', 'Face & Return', 'face-return', 'After Cutting', 'after-cutting', 'plastic', '[6]'),
('Substrate Cut', 'substrate-cut', 'Face & Return', 'face-return', 'After Bending', 'after-bending', 'plastic', NULL),
('Substrate Cut', 'substrate-cut', 'Face & Return', 'face-return', 'After Fabrication', 'after-fabrication', 'plastic', '[8]'),
('Substrate Cut', 'substrate-cut', 'Frame', 'frame', 'Before Cutting', 'before-cutting', 'plastic', NULL),
('Substrate Cut', 'substrate-cut', 'Frame', 'frame', 'After Cutting', 'after-cutting', 'plastic', NULL),
('Substrate Cut', 'substrate-cut', 'Frame', 'frame', 'After Bending', 'after-bending', 'plastic', NULL),
('Substrate Cut', 'substrate-cut', 'Frame', 'frame', 'After Fabrication', 'after-fabrication', 'plastic', NULL),
('Substrate Cut', 'substrate-cut', 'All Sides', 'all-sides', 'Before Cutting', 'before-cutting', 'plastic', NULL),
('Substrate Cut', 'substrate-cut', 'All Sides', 'all-sides', 'After Cutting', 'after-cutting', 'plastic', '[6]'),
('Substrate Cut', 'substrate-cut', 'All Sides', 'all-sides', 'After Bending', 'after-bending', 'plastic', '[7]'),
('Substrate Cut', 'substrate-cut', 'All Sides', 'all-sides', 'After Fabrication', 'after-fabrication', 'plastic', '[8]'),

-- =============================================================================
-- Backer - Flat variant
-- =============================================================================
('Backer', 'backer', 'Face', 'face', 'Before Cutting', 'before-cutting', 'flat', '[2,3]'),
('Backer', 'backer', 'Face', 'face', 'After Cutting', 'after-cutting', 'flat', '[2,6]'),
('Backer', 'backer', 'Face', 'face', 'After Bending', 'after-bending', 'flat', '[2,7]'),
('Backer', 'backer', 'Face', 'face', 'After Fabrication', 'after-fabrication', 'flat', '[2,8]'),
('Backer', 'backer', 'Return', 'return', 'Before Cutting', 'before-cutting', 'flat', '[1,3]'),
('Backer', 'backer', 'Return', 'return', 'After Cutting', 'after-cutting', 'flat', '[4,6]'),
('Backer', 'backer', 'Return', 'return', 'After Bending', 'after-bending', 'flat', NULL),
('Backer', 'backer', 'Return', 'return', 'After Fabrication', 'after-fabrication', 'flat', '[4,8]'),
('Backer', 'backer', 'Trim', 'trim', 'Before Cutting', 'before-cutting', 'flat', NULL),
('Backer', 'backer', 'Trim', 'trim', 'After Cutting', 'after-cutting', 'flat', NULL),
('Backer', 'backer', 'Trim', 'trim', 'After Bending', 'after-bending', 'flat', NULL),
('Backer', 'backer', 'Trim', 'trim', 'After Fabrication', 'after-fabrication', 'flat', NULL),
('Backer', 'backer', 'Return & Trim', 'return-trim', 'Before Cutting', 'before-cutting', 'flat', NULL),
('Backer', 'backer', 'Return & Trim', 'return-trim', 'After Cutting', 'after-cutting', 'flat', NULL),
('Backer', 'backer', 'Return & Trim', 'return-trim', 'After Bending', 'after-bending', 'flat', NULL),
('Backer', 'backer', 'Return & Trim', 'return-trim', 'After Fabrication', 'after-fabrication', 'flat', NULL),
('Backer', 'backer', 'Face & Return', 'face-return', 'Before Cutting', 'before-cutting', 'flat', '[1,2,3]'),
('Backer', 'backer', 'Face & Return', 'face-return', 'After Cutting', 'after-cutting', 'flat', '[2,4,6]'),
('Backer', 'backer', 'Face & Return', 'face-return', 'After Bending', 'after-bending', 'flat', NULL),
('Backer', 'backer', 'Face & Return', 'face-return', 'After Fabrication', 'after-fabrication', 'flat', '[4,8]'),
('Backer', 'backer', 'Frame', 'frame', 'Before Cutting', 'before-cutting', 'flat', NULL),
('Backer', 'backer', 'Frame', 'frame', 'After Cutting', 'after-cutting', 'flat', NULL),
('Backer', 'backer', 'Frame', 'frame', 'After Bending', 'after-bending', 'flat', NULL),
('Backer', 'backer', 'Frame', 'frame', 'After Fabrication', 'after-fabrication', 'flat', NULL),
('Backer', 'backer', 'All Sides', 'all-sides', 'Before Cutting', 'before-cutting', 'flat', '[1,2,3]'),
('Backer', 'backer', 'All Sides', 'all-sides', 'After Cutting', 'after-cutting', 'flat', '[2,4,6]'),
('Backer', 'backer', 'All Sides', 'all-sides', 'After Bending', 'after-bending', 'flat', NULL),
('Backer', 'backer', 'All Sides', 'all-sides', 'After Fabrication', 'after-fabrication', 'flat', '[4,8]'),

-- =============================================================================
-- Backer - Folded variant
-- =============================================================================
('Backer', 'backer', 'Face', 'face', 'Before Cutting', 'before-cutting', 'folded', '[2,3]'),
('Backer', 'backer', 'Face', 'face', 'After Cutting', 'after-cutting', 'folded', '[2,6]'),
('Backer', 'backer', 'Face', 'face', 'After Bending', 'after-bending', 'folded', '[2,7]'),
('Backer', 'backer', 'Face', 'face', 'After Fabrication', 'after-fabrication', 'folded', '[2,8]'),
('Backer', 'backer', 'Return', 'return', 'Before Cutting', 'before-cutting', 'folded', '[2,3]'),
('Backer', 'backer', 'Return', 'return', 'After Cutting', 'after-cutting', 'folded', NULL),
('Backer', 'backer', 'Return', 'return', 'After Bending', 'after-bending', 'folded', '[2,7]'),
('Backer', 'backer', 'Return', 'return', 'After Fabrication', 'after-fabrication', 'folded', '[2,8]'),
('Backer', 'backer', 'Trim', 'trim', 'Before Cutting', 'before-cutting', 'folded', NULL),
('Backer', 'backer', 'Trim', 'trim', 'After Cutting', 'after-cutting', 'folded', NULL),
('Backer', 'backer', 'Trim', 'trim', 'After Bending', 'after-bending', 'folded', NULL),
('Backer', 'backer', 'Trim', 'trim', 'After Fabrication', 'after-fabrication', 'folded', NULL),
('Backer', 'backer', 'Return & Trim', 'return-trim', 'Before Cutting', 'before-cutting', 'folded', NULL),
('Backer', 'backer', 'Return & Trim', 'return-trim', 'After Cutting', 'after-cutting', 'folded', NULL),
('Backer', 'backer', 'Return & Trim', 'return-trim', 'After Bending', 'after-bending', 'folded', NULL),
('Backer', 'backer', 'Return & Trim', 'return-trim', 'After Fabrication', 'after-fabrication', 'folded', NULL),
('Backer', 'backer', 'Face & Return', 'face-return', 'Before Cutting', 'before-cutting', 'folded', '[2,3]'),
('Backer', 'backer', 'Face & Return', 'face-return', 'After Cutting', 'after-cutting', 'folded', NULL),
('Backer', 'backer', 'Face & Return', 'face-return', 'After Bending', 'after-bending', 'folded', '[5,7]'),
('Backer', 'backer', 'Face & Return', 'face-return', 'After Fabrication', 'after-fabrication', 'folded', '[5,8]'),
('Backer', 'backer', 'Frame', 'frame', 'Before Cutting', 'before-cutting', 'folded', NULL),
('Backer', 'backer', 'Frame', 'frame', 'After Cutting', 'after-cutting', 'folded', NULL),
('Backer', 'backer', 'Frame', 'frame', 'After Bending', 'after-bending', 'folded', NULL),
('Backer', 'backer', 'Frame', 'frame', 'After Fabrication', 'after-fabrication', 'folded', NULL),
('Backer', 'backer', 'All Sides', 'all-sides', 'Before Cutting', 'before-cutting', 'folded', '[2,3]'),
('Backer', 'backer', 'All Sides', 'all-sides', 'After Cutting', 'after-cutting', 'folded', NULL),
('Backer', 'backer', 'All Sides', 'all-sides', 'After Bending', 'after-bending', 'folded', '[5,7]'),
('Backer', 'backer', 'All Sides', 'all-sides', 'After Fabrication', 'after-fabrication', 'folded', '[5,8]');

-- Set all entries as active
UPDATE painting_task_matrix SET is_active = TRUE WHERE is_active IS NULL;
